upx:
  - enabled: true
    lzma: true
    compress: best
    goos: [linux]

archives:
- format: binary

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

release:
  gitlab:
    owner: gitlab-com/pepa65
    name: stock

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

gitlab_urls:
  api: '{{ .Env.CI_SERVER_URL }}'
  download: '{{ .Env.CI_SERVER_URL }}'
